### PR TITLE
Add German translation

### LINKED ISSUE #23: Translate this project to German
This project hasn't been active in years but I wanted to ask anyway if you would like me to translate this project to German. 
Thank you very much for creating such a beautiful open-source game.

WebSnke

### PR DESCRIPTION
**Pull request by psjnek**
Resolve #23.

### CODE REVIEW

**Comment by psjnek** [comment]
@evanbowman
Could you take a look at my changes, please?

**Comment by evanbowman** [comment]
yeah of course! I'll try to finish reviewing it sometime in the next couple days

**Comment by verkkarscd** [comment]
Wow, this must be have most languages gba the game

**Comment by evanbowman** [comment]
@WebSnke I haven't finished reviewing yet, but here's the ROM.
[BlindJump.zip](https://github.com/evanbowman/blind-jump-portable/files/11615720/BlindJump.zip)
There are just a few places where the text doesn't fit onscreen. For example:

BlindJump-81
BlindJump-80
BlindJump-78

**Comment by psjnek** [comment]
> @WebSnke I haven't finished reviewing yet, but here's the ROM. [BlindJump.zip](https://github.com/evanbowman/blind-jump-portable/files/11615720/BlindJump.zip) There are just a few places where the text doesn't fit onscreen. For example:
> 
> BlindJump-81 BlindJump-80 BlindJump-78

Thanks. I will try to resolve the issue.

**Comment by evanbowman** [comment]
Thanks for continuing to work on this! I've been busy and haven't had a chance to review again yet. Since the last release a couple of years ago I've updated my compiler and the game crashes unexpectedly in one spot, so I have to find a chance to debug the issue before releasing again

**Comment by psjnek** [comment]
@evanbowman 
Hi, I just tried to compile the ROM but it didn't work with docker. Can I compile it without Docker somehow?

**Comment by evanbowman** [comment]
> @evanbowman Hi, I just tried to compile the ROM but it didn't work with docker. Can I compile it without Docker somehow?

Hi! Sorry, the docker environment must be out of date! I intended to make it easier for people to contribute to the project with the container environment, but it hasn't worked out as well as I expected.

To compile without docker, first, you'll want to install the devkitarm toolchain, which includes a cross compiler for generating GBA-compatible machine code. To install devkitarm, follow these instructions:
https://devkitpro.org/wiki/Getting_Started

After installing devkitarm, clone this repository. I've made all of the code changes so far on a branch called german-upstream. To integrate your text file, update your repository from the fork, merge `german-upstream` branch into your own `german` branch. If you have any trouble merging, let me know and I can give some suggestions. Alternatively, you can change the base branch of this PR on the github website to `german-upstream`, I can approve the merge, and we can continue work in a new subsequent PR.

Finally, to build the code, you would want to run the following commands in the command line:
```
cd blind-jump-portable/build
./set-gameboy-advance-toolchain
make
```

**Comment by evanbowman** [comment]
See [here](https://github.com/evanbowman/blind-jump-portable/commit/e127bcc7829aaef65295386df4486cc7f7ca5701) in case you have trouble finding the branch.

**Comment by psjnek** [comment]
I just can't get it running on my machine...

```bash
╰─ sudo bash set-gameboy-advance-toolchain.sh                                                                                                                                                      ─╯
CMake Error at devkitarm.cmake:7 (message):
  Please set DEVKITARM in your environment
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:3 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

Could you maybe compile it for me?

**Comment by evanbowman** [comment]
"Please set DEVKITARM in your environment"

export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITPPC=${DEVKITPRO}/devkitPPC

**Comment by evanbowman** [comment]
[Uploading BlindJump.zip…]()
Here is the compiled rom as well

**Comment by evanbowman** [comment]
Also, here is the compiled rom:
[BlindJump.zip](https://github.com/evanbowman/blind-jump-portable/files/11983951/BlindJump.zip)
The translation was missing one line in the file, at line 80 (the night-mode settings text)

**Comment by psjnek** [comment]
> > @WebSnke I haven't finished reviewing yet, but here's the ROM. [BlindJump.zip](https://github.com/evanbowman/blind-jump-portable/files/11615720/BlindJump.zip) There are just a few places where the text doesn't fit onscreen. For example:
> > BlindJump-81 BlindJump-80 BlindJump-78
> 
> Thanks. I will try to resolve the issue.

I really tried my best to find alternative translations and it is now `item + "erhalten"`. Sometimes it fits on the screen, sometimes it doesn't.

**Comment by psjnek** [comment]
> Thanks for continuing to work on this! I've been busy and haven't had a chance to review again yet. Since the last release a couple of years ago I've updated my compiler and the game crashes unexpectedly in one spot, so I have to find a chance to debug the issue before releasing again

Even though the code is a bit broken, I think this PR is ready to be merged. 
Right? Did I miss anything?

**Comment by evanbowman** [comment]
Yeah, I think it's about ready! I will merge it soon, but I will not be able to release the ROM until I have a chance to debug some crashes that started happening after upgrading my compiler.

**Comment by psjnek** [comment]
You are the nicest maintainers I have ever meet on GitHub btw.

**Pull request merged**
